FROM fedora:latest

# build tools
# SSL and Vulcan SDK dependencies
RUN dnf update -y \
    && \
    dnf install -y 'dnf-command(config-manager)' \
    && \
    dnf config-manager addrepo --from-repofile https://developer.download.nvidia.com/compute/cuda/repos/fedora43/x86_64/cuda-fedora43.repo
RUN dnf update -y \
    && \
    dnf install -y \
        \
        git gcc gcc-c++ \
        make \
        cmake \
        wget \
        xz \
        \
        openssl-devel \
        curl \
        libxcb \
        libXinerama \
        xcb-util-cursor-devel \
        vulkan-loader-devel \
        glslc \
        spirv-headers-devel \
	\
        cuda-toolkit

RUN echo "export PATH=/usr/local/cuda/bin:$PATH" > /etc/profile.d/zzz_cuda.sh
RUN echo "/usr/local/cuda/lib64" > /etc/ld.so.conf.d/usr_local_cuda.conf && ldconfig

# Match these to your host user's UID/GID.
ARG USERNAME=llama_dev
ARG USER_UID=1000
ARG USER_GID=1000

RUN groupadd --gid $USER_GID $USERNAME && \
    useradd --uid $USER_UID --gid $USER_GID --shell /bin/bash --create-home $USERNAME

WORKDIR /app

RUN mkdir -p /app && chown $USER_UID:$USER_GID /app

USER $USERNAME

CMD ["bash"]
